# Generated by Django 5.2.5 on 2025-08-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome do banner (ex: Banner de Promoção)', max_length=200)),
                ('descricao', models.TextField(help_text='Uma descrição curta sobre o banner.')),
                ('imagem', models.ImageField(help_text='A imagem do banner.', upload_to='banners/')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o banner está ativo e deve ser exibido.')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='O nome da categoria. Deve ser único.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Uma breve descrição da categoria.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Uma imagem para representar a categoria.', null=True, upload_to='categories/')),
                ('active', models.BooleanField(default=True, help_text='Indica se a categoria está ativa e deve ser exibida.')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Preço Principal')),
                ('price2', models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Preço Adicional')),
                ('image', models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pages.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.PositiveIntegerField(default=1, verbose_name='Qtde')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
    ]
