# Generated by Django 5.2.5 on 2025-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='telefone',
        ),
    ]
