# Generated by Django 5.2.5 on 2025-08-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
