# Generated by Django 5.2.5 on 2025-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_order_created_at_order_user_alter_order_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referencia',
            field=models.TextField(default=2, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
