# Generated by Django 5.2.5 on 2025-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='referencia',
            field=models.CharField(max_length=40, verbose_name='Referencia'),
        ),
    ]
