# Generated by Django 5.2.5 on 2025-08-20 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_product_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
